# Site settings
title: Rebecca Jaszczak
author: Rebecca Jaszczak 
description: "data scientist by day, artist by night"
url: "https://rebeccagj.github.io/"
date_format: "%b %-d, %Y"
markdown: kramdown

logo: /assets/img/profileimage.jpeg
show_downloads: true
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: 
google_tag_manager:

# Social icons
github_username:   rebeccagj 
stackoverflow_id:  rebeccagj
twitter_username:  rzbzz
linkedin_username: rebecca-jaszczak
